import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-5xl">
        <h1>Hello Tailwindcss</h1>
      </main>

      <footer>
      </footer>
    </div>
  )
}
