import Head from "next/head";
import Hero from "../components/hero.js";
import Carousel from "../components/carousel.js";

export default function Home() {
    return (
        <div data-theme="dark">
            <Head>
                <title>Nonfunge Land</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="">
                <Hero />
                <Carousel />
            </main>
            <footer></footer>
        </div>
    );
}
